/det/select Box

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select range

/gen/range/id 11
/gen/range/t0 0 ns
/gen/range/vertex 120 0 20 m
/gen/range/p_unit 0 0 -1

/gen/range/phi_min -1.7 rad
/gen/range/phi_max  1.7 rad
/gen/range/eta_min -1.6
/gen/range/eta_max  1.6

/gen/range/p_mag {pmag} GeV/c

/run/beamOn {count}
