/det/select Box

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select pythia
/gen/pythia/add_filter displaced
/gen/pythia/read_file studies/box/signal/hh_to_bbbar_ctau50.cmnd

/run/beamOn 500000
