/det/select Box

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select pythia
/gen/pythia/add_filter promptmuon
/gen/pythia/read_file studies/box/signal/w_to_muon.cmnd

/run/beamOn 1000
