#!/bin/bash

/home/ag1378/cmslink/bobthebuilder/Mu-Simulation_full_bottom_scint/./simulation -o /home/ag1378/cmslink/bobthebuilder/simulation_service/projects/background/data/ -s /home/ag1378/cmslink/bobthebuilder/Mu-Simulation_full_bottom_scint/studies/box/background/run_pythia_w.mac
