/det/select Box

/vis/filtering/trajectories/create/chargeFilter
/vis/filtering/trajectories/chargeFilter-0/add 0
/vis/filtering/trajectories/chargeFilter-0/invert true
/vis/filtering/trajectories/chargeFilter-0/verbose false
/vis/filtering/trajectories/chargeFilter-0/active true

/gen/select pythia
/gen/pythia/add_filter promptmuon
/gen/pythia/read_file studies/box/background/w_to_muon.cmnd

/analysis/setFileName Muon
/analysis/h1/set 0 100 -100000 100000 cm #X_Value
/analysis/h1/set 1 100 -100000 100000 cm #Y_Value
/analysis/h1/set 2 100 -100000 100000 cm #Z_Value


/run/beamOn 100000
